### Get all books
GET http://localhost:3000/api/books 
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGFhMzRhODY4MDRkYjFmNmM5OTQzZjQiLCJpYXQiOjE2MjE3NjgxODk2NzQsImV4cCI6MTYyMTc2ODI3NjA3NH0.DbdotEmgPGJZOPTY-lKmw44suhT_dmLWjbJQkaxzVYPV64RJeuISZVpDbrHW5PrjFF9tq-rO6chqiS2ANUTrxvvI-JqVWNm7IvqUUSpGKgMl-tl54oz3lvUboPfCmCgse8Mz35TlKARlDfx35EF4tistWBbt3AZnQ06Juc5Av2s4qNs6DLYFBFz_x1iDGVUJfzK7qPUw-jj8J2NHAPmcGfclhSm77N7n1o6Pbps3XSRaNntyOBst6GtKhCW8eRpx5U3O5csqW0fEENDQxGZUHrJjVNFc3GiymezkGZSA_OLKFqonhEYdGbQ15m2k3oG930kpS9cfmmhBOlInbKjHHKTwG3d2uoHl7WIIzWeqzLCQDxAJBKgsu6SUXTsInmkWJ8sGcGbnXoNKj60iYscQ30uLf8nfhtN2vhqvfynnp9Z3Mdg-hhbX3cM1VX3J-3nIkhwMhjP_ieuAzZ1mjNihaHzxT-hv87XdtsnBc9lUDRY4jE-8vQNAEIXvhxI12dmwZVu0SvYPpRY-sh7e1eeFaj26pmS1ytDjG1DUSXCCq3PEWI0TnsYqwmPxuVcO6yiyFSONLpNtPRAfHxXZQgYFr3tfG398VXmnRB8eU0uERdKmiBZC4Qs8S7MiK8wX_7tBAVMJZGEfa6A9tENQo37lBWzE6dwcNxuyh7TrZF2Xb9Q


### Get a single book
GET http://localhost:3000/api/books/60aa840d12654934ab699cb8
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGFhMzRhODY4MDRkYjFmNmM5OTQzZjQiLCJpYXQiOjE2MjE3NjgxODk2NzQsImV4cCI6MTYyMTc2ODI3NjA3NH0.DbdotEmgPGJZOPTY-lKmw44suhT_dmLWjbJQkaxzVYPV64RJeuISZVpDbrHW5PrjFF9tq-rO6chqiS2ANUTrxvvI-JqVWNm7IvqUUSpGKgMl-tl54oz3lvUboPfCmCgse8Mz35TlKARlDfx35EF4tistWBbt3AZnQ06Juc5Av2s4qNs6DLYFBFz_x1iDGVUJfzK7qPUw-jj8J2NHAPmcGfclhSm77N7n1o6Pbps3XSRaNntyOBst6GtKhCW8eRpx5U3O5csqW0fEENDQxGZUHrJjVNFc3GiymezkGZSA_OLKFqonhEYdGbQ15m2k3oG930kpS9cfmmhBOlInbKjHHKTwG3d2uoHl7WIIzWeqzLCQDxAJBKgsu6SUXTsInmkWJ8sGcGbnXoNKj60iYscQ30uLf8nfhtN2vhqvfynnp9Z3Mdg-hhbX3cM1VX3J-3nIkhwMhjP_ieuAzZ1mjNihaHzxT-hv87XdtsnBc9lUDRY4jE-8vQNAEIXvhxI12dmwZVu0SvYPpRY-sh7e1eeFaj26pmS1ytDjG1DUSXCCq3PEWI0TnsYqwmPxuVcO6yiyFSONLpNtPRAfHxXZQgYFr3tfG398VXmnRB8eU0uERdKmiBZC4Qs8S7MiK8wX_7tBAVMJZGEfa6A9tENQo37lBWzE6dwcNxuyh7TrZF2Xb9Q


